name: Build OnePlus N200 Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential flex libssl-dev libncurses5-dev wget unzip zip tar xz-utils

      - name: Download Proton Clang
        run: |
          wget https://github.com/kdrag0n/proton-clang/releases/latest/download/proton-clang-linux-x86.tar.xz -O proton-clang.tar.xz
          mkdir -p $HOME/proton-clang
          tar -xf proton-clang.tar.xz -C $HOME/proton-clang
          echo "$HOME/proton-clang/bin" >> $GITHUB_PATH

      - name: Build Kernel
        run: |
          cd dre-kernel-source
          export ARCH=arm64
          export O=out
          make O=$O dre_defconfig
          make -j$(nproc) O=$O CC=clang

      - name: Package AnyKernel3
        run: |
          mkdir -p kernel-zip
          cp dre-kernel-source/out/arch/arm64/boot/Image.gz-dtb kernel-zip/
          cp -r AnyKernel3/* kernel-zip/
          zip -r kernel-build.zip kernel-zip/
          mv kernel-build.zip $GITHUB_WORKSPACE/kernel-build.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: kernel-build.zip