name: Build OnePlus N200 Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential flex libssl-dev libncurses5-dev wget unzip zip

      - name: Download Clang
        run: |
          wget https://github.com/lollol911/dre-kernel-android15/releases/download/clang/linux-x86-722c840a8e4d58b5ebdab62ce78eacdafd301208-clang-r450784e.tar.gz -O clang.tar.gz
          mkdir -p $HOME/clang-toolchain
          tar -xf clang.tar.gz -C $HOME/clang-toolchain
          echo "$HOME/clang-toolchain/bin" >> $GITHUB_PATH

      - name: Build Kernel
        run: |
          cd dre-kernel-source
          export ARCH=arm64
          export O=out
          export PATH=$HOME/clang-toolchain/bin:$PATH
          export CC=clang
          export LD=ld.lld
          export CROSS_COMPILE=aarch64-linux-gnu-
          # Generate .config from dre_defconfig
          make O=$O ARCH=$ARCH KCONFIG_CONFIG=arch/arm64/configs/dre_defconfig olddefconfig
          # Build the kernel
          make -j$(nproc) O=$O ARCH=$ARCH CC=$CC LD=$LD CROSS_COMPILE=$CROSS_COMPILE

      - name: Package AnyKernel3
        run: |
          mkdir -p kernel-zip
          cp dre-kernel-source/out/arch/arm64/boot/Image.gz-dtb kernel-zip/
          cp -r AnyKernel3/* kernel-zip/
          zip -r kernel-build.zip kernel-zip/
          mv kernel-build.zip $GITHUB_WORKSPACE/kernel-build.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: kernel-build.zip